version: '3.8'

services:
  product_db:
    image: postgres:14
    container_name: product_db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
    volumes:
      - product_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_user -d product_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  product_service:
    build: .
    container_name: product_service
    environment:
      DATABASE_URL: postgresql://product_user:product_password@product_db:5432/product_db
    ports:
      - "8000:8000"
    depends_on:
      product_db:
        condition: service_healthy
    command: poetry run uvicorn product_service.main:app --host 0.0.0.0 --port 8000

volumes:
  product_db_data: